export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'

export const PUT_DATA_START = 'PUT_DATA_START';
export const PUT_DATA_SUCCESS = 'PUT_DATA_SUCCESS'
export const PUT_DATA_FAIL = 'PUT_DATA_FAIL'

export const PUSH_DATA_START = 'PUSH_DATA_START';
export const PUSH_DATA_SUCCESS = 'PUSH_DATA_SUCCESS'
export const PUSH_DATA_FAIL = 'PUSH_DATA_FAIL'

export const DELETE_DATA_START = 'DELETE_DATA_START';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS'
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL'